# -*- mode: python ; coding: utf-8 -*-
import os
import sys
import glob

block_cipher = None

# Get absolute path to src directory
src_path = os.path.abspath('src')

# Collect data files (soundfont, icons, and documentation)
datas = [
    ('resources/soundfont/GeneralUser-GS.sf2', 'resources/soundfont'),
    ('resources/icon-32.png', 'resources'),
    ('resources/icon-128.png', 'resources'),
    ('resources/icon-256.png', 'resources'),
    ('resources/icons', 'resources/icons'),
    # Bundle HTML documentation for in-app help
    ('help/build/html', 'help/build/html'),
]

# Collect FluidSynth DLLs on Windows
binaries = []
if sys.platform == 'win32':
    # Look for FluidSynth DLLs in the environment variable set by the build workflow
    fluidsynth_path = os.environ.get('FLUIDSYNTH_PATH', '')
    if fluidsynth_path and os.path.isdir(fluidsynth_path):
        # Collect all DLLs from the FluidSynth bin directory
        for dll in glob.glob(os.path.join(fluidsynth_path, '*.dll')):
            binaries.append((dll, 'fluidsynth'))
        print(f"Found {len(binaries)} FluidSynth DLLs in {fluidsynth_path}")
    else:
        # Try common local development paths (cwd is the project root when
        # PyInstaller exec()s this spec; __file__ is not defined in that context).
        local_paths = [
            os.path.abspath(os.path.join('.tools', 'bin')),
            r'C:\tools\fluidsynth\bin',
        ]
        for path in local_paths:
            if os.path.isdir(path):
                for dll in glob.glob(os.path.join(path, '*.dll')):
                    binaries.append((dll, 'fluidsynth'))
                print(f"Found {len(binaries)} FluidSynth DLLs in {path}")
                break
        if not binaries:
            print("WARNING: FluidSynth DLLs not found. Set FLUIDSYNTH_PATH or install to C:\\tools\\fluidsynth")

# Runtime hooks - handle FluidSynth DLL loading on Windows
runtime_hooks = []
if sys.platform == 'win32':
    runtime_hooks.append('hooks/hook-fluidsynth.py')

# Windows exe version metadata (Explorer Properties -> Details).
# Generated by the CI workflow; absent on local dev builds. PyInstaller exec()s
# this spec, so __file__ is not defined - rely on cwd being the project root
# (matches how other paths in this spec are resolved).
win_version_file = None
if sys.platform == 'win32':
    candidate = os.path.abspath('version_info.txt')
    if os.path.isfile(candidate):
        win_version_file = candidate
        print(f"Using Windows version info file: {candidate}")
    else:
        print("No version_info.txt found - Windows exe will have no embedded version metadata")

# Hidden imports - all our local modules
hiddenimports = [
    'ui',
    'ui.main_window',
    'ui.text_editor',
    'ui.help_window',
    'audio',
    'audio.player',
    'audio.chord_picker',
    'chord',
    'chord.converter',
    # PIL.ImageTk imports this lazily at runtime to bridge Pillow and Tk;
    # PyInstaller can't see it via static analysis, so the frozen build fails
    # with "No module named 'PIL._tkinter_finder'" when loading toolbar icons.
    'PIL._tkinter_finder',
]

# Exclude unused GUI frameworks
excludes = [
    'PyQt5',
    'PyQt6',
    'PySide2',
    'PySide6',
    'wx',
]

a = Analysis(
    ['src/main.py'],
    pathex=[src_path],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=runtime_hooks,
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ChordNotepad',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window for GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/chord-notepad-icon.ico',  # Windows icon
    version=win_version_file,  # Embedded VS_VERSION_INFO on Windows
)
